
services:
    app:
      build: .
      ports: ["8080:80"]
      volumes:
        - ./:/var/www/html          # Mapeia todo o projeto
        - ./php/php.ini:/usr/local/etc/php/conf.d/custom.ini
        - ./docker/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      depends_on:
        - db
  
    db:
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: app_db
        MYSQL_USER: dev
        MYSQL_PASSWORD: dev123
      volumes:
        - mysql_data:/var/lib/mysql
  
  volumes:
    mysql_data: