services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php_study_app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      db:
        condition: service_healthy
    networks:
      - php_network
    restart: unless-stopped

  db:
    image: mariadb:10.6
    container_name: php_study_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app_db
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev123
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/backups:/backups
    ports:
      - "3306:3306"
    networks:
      - php_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: php_study_adminer
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - php_network
    restart: unless-stopped

networks:
  php_network:
    driver: bridge

volumes:
  mysql_data:
